language: php

php:
  - 7.2

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest
  - cp .env.example .env

script:
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)